## Stage1:生成模型



#### 导入包

In [1]:
from skimage.transform import rotate
from skimage.feature import local_binary_pattern
from skimage import data, io
from skimage.color import label2rgb
import skimage
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import cv2
%matplotlib inline
import glob as gb
import mahotas

In [2]:
#def LBPhist(image):
    # settings for LBP
#    radius = 3
#    n_points = 8 * radius
    # 转换为灰度图显示
#    image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    # 处理
#    lbp = local_binary_pattern(image, n_points, radius)
#    bins = np.arange(257)
#    hist,bins = np.histogram(lbp,bins)
#    return hist

In [3]:
from skimage import feature
def LBP_describe(image, eps=1e-7):
    # compute the Local Binary Pattern representation
    # of the image, and then use the LBP representation
    # to build the histogram of patterns
    lbp = feature.local_binary_pattern(image,8,
    3, method="uniform")
    (hist, _) = np.histogram(lbp.ravel(),
    bins=np.arange(0, 8 + 3),
    range=(0, 8 + 2))
    # normalize the histogram
    hist = hist.astype("float")
    hist /= (hist.sum() + eps)
    # return the histogram of Local Binary Patterns
    return hist

In [4]:
def fd_hu_moments(image):
    #image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    feature = cv2.HuMoments(cv2.moments(image)).flatten()
    return feature

In [5]:
def fd_haralick(image):
    # convert the image to grayscale
    #gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # compute the haralick texture feature vector
    haralick = mahotas.features.haralick(image).mean(axis=0)
    # return the result
    return haralick

In [6]:
def feature_ex(image):
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    hist_lbp = LBP_describe(gray)#10
    hist_hu = fd_hu_moments(gray)#7
    hist_hara = fd_haralick(gray)#13
    hist_feature = np.hstack([hist_lbp, hist_hu, hist_hara])
    return hist_feature

### 测试LBP

#### train_smoke

In [7]:
img_path_train_smoke = gb.glob("F:\\smokeproject\\sets\\set1\\smoke\\*.jpg") 
num_length_train_smoke = len(img_path_train_smoke)
hist_empty = np.zeros([1,30])
y_train_smoke = np.ones([num_length_train_smoke,1])

for path in img_path_train_smoke:
    img  = cv2.imread(path) 
    hist = feature_ex(img)
    hist_empty = np.vstack((hist_empty, hist))
    
train_smoke = hist_empty[1:,:]

In [8]:
##test
hist_empty[1:,:]

array([[ 0.06032986,  0.08072917,  0.07248264, ...,  3.58456127,
        -0.3551944 ,  0.99316825],
       [ 0.06076389,  0.09027778,  0.11935764, ...,  3.67082602,
        -0.36102912,  0.99363858],
       [ 0.05425347,  0.08333333,  0.1171875 , ...,  3.53583028,
        -0.37326724,  0.99487622],
       ...,
       [ 0.04817708,  0.07552083,  0.09375   , ...,  3.42987408,
        -0.48210843,  0.99937865],
       [ 0.04730903,  0.0625    ,  0.09027778, ...,  4.00040104,
        -0.42660242,  0.9986648 ],
       [ 0.05381944,  0.08029514,  0.10286458, ...,  3.82322316,
        -0.33687836,  0.99156766]])

#### train_no_smoke

In [9]:
img_path_train_no_smoke = gb.glob("F:\\smokeproject\\sets\\set1\\non\\*.jpg") 
num_length_train_no_smoke = len(img_path_train_no_smoke)
hist_empty = np.zeros([1,30])
y_train_no_smoke = np.zeros([num_length_train_no_smoke,1])

for path in img_path_train_no_smoke:
    img  = cv2.imread(path) 
    hist = feature_ex(img)
    hist_empty = np.vstack((hist_empty, hist))
    
train_no_smoke = hist_empty[1:,:]

train_no_smoke

array([[ 0.07508681,  0.10763889,  0.05555556, ...,  2.59561579,
        -0.38036578,  0.98139839],
       [ 0.10503472,  0.10590278,  0.05642361, ...,  4.52554634,
        -0.34475946,  0.99282371],
       [ 0.08029514,  0.12065972,  0.05295139, ...,  3.30321451,
        -0.30577738,  0.97778351],
       ...,
       [ 0.10763889,  0.13020833,  0.06467014, ...,  5.00184454,
        -0.2572512 ,  0.98041864],
       [ 0.08854167,  0.11371528,  0.06987847, ...,  4.2117168 ,
        -0.33210141,  0.99170015],
       [ 0.11371528,  0.14149306,  0.04600694, ...,  5.65272197,
        -0.35932864,  0.99691454]])

#### test_smoke

In [10]:
img_path_test_smoke = gb.glob("F:\\smokeproject\\sets\\set2\\smoke\\*.jpg") 
num_length_test_smoke = len(img_path_test_smoke)
hist_empty = np.zeros([1,30])
y_test_smoke = np.ones([num_length_test_smoke,1])

for path in img_path_test_smoke:
    img  = cv2.imread(path) 
    hist = feature_ex(img)
    hist_empty = np.vstack((hist_empty, hist))
    
test_smoke = hist_empty[1:,:]

#### test_no_smoke

In [11]:
img_path_test_no_smoke = gb.glob("F:\\smokeproject\\sets\\set2\\non\\*.jpg") 
num_length_test_no_smoke = len(img_path_test_no_smoke)
hist_empty = np.zeros([1,30])
y_test_no_smoke = np.zeros([num_length_test_no_smoke,1])

for path in img_path_test_no_smoke:
    img  = cv2.imread(path) 
    hist = feature_ex(img)
    hist_empty = np.vstack((hist_empty, hist))
    
test_no_smoke = hist_empty[1:,:]

test_no_smoke

array([[ 0.11848958,  0.11284722,  0.04600694, ...,  4.31143918,
        -0.3475575 ,  0.9942231 ],
       [ 0.07074653,  0.12630208,  0.07769097, ...,  4.29193077,
        -0.37618593,  0.99515567],
       [ 0.09592014,  0.10026042,  0.0625    , ...,  5.08573798,
        -0.4582644 ,  0.99938226],
       ...,
       [ 0.06727431,  0.11762153,  0.07899306, ...,  4.75680115,
        -0.33865202,  0.99391296],
       [ 0.0625    ,  0.10633681,  0.04991319, ...,  4.39441214,
        -0.30668938,  0.98809266],
       [ 0.06944444,  0.11805556,  0.05642361, ...,  4.84767869,
        -0.48524513,  0.99954971]])

#### 连接矩阵

In [12]:
#np.concatenate((a,b),axis=0)

In [13]:
#连接矩阵并转换格式
y_train = np.vstack((y_train_smoke, y_train_no_smoke))
X_train = np.vstack((train_smoke,train_no_smoke))

y_train = y_train.astype(np.int64)

In [14]:
y_test = np.vstack((y_test_smoke, y_test_no_smoke))
X_test = np.vstack((test_smoke,test_no_smoke))

y_test = y_test.astype(np.int64)

In [15]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1383, 30)
(1383, 1)
(1505, 30)
(1505, 1)


#### 打乱排序

In [16]:
#all_xys = np.hstack((X_train,y_train))

In [17]:
indices = np.random.permutation(X_train.shape[0]) # shape[0]表示第0轴的长度，通常是训练数据的数量
rand_data_x = X_train[indices]
rand_data_y = y_train[indices] # data_y就是标记（label）

In [18]:
from sklearn.model_selection import train_test_split
cro_X_train, cro_X_test, cro_y_train, cro_y_test = train_test_split(rand_data_x, rand_data_y, test_size = 0.25, random_state = 0)


#### SVM分类器

In [20]:
y_train = y_train.ravel()#将y由列向量变为行向量

In [19]:
from sklearn.svm import SVC
SVMclassifier = SVC(kernel = 'linear', random_state = 0,C = 10)
SVMclassifier.fit(X_train, y_train)

E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [21]:
# Predicting the Test set results
SVM_y_pred = SVMclassifier.predict(X_test)

# Making the Confusion Matrix 混淆矩阵
from sklearn.metrics import confusion_matrix
SVMcm = confusion_matrix(y_test, SVM_y_pred)

In [22]:
SVMcm

array([[745,  72],
       [ 60, 628]], dtype=int64)

#### SVC 调参

In [57]:
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]
scores = ['precision', 'recall']

In [58]:
for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()
     # 调用 GridSearchCV，将 SVC(), tuned_parameters, cv=5, 还有 scoring 传递进去，
    clf = GridSearchCV(SVC(), tuned_parameters, cv=5,
                       scoring='%s_macro' % score,n_jobs = -1)
    # 用训练集训练这个学习器 clf
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()

    # 再调用 clf.best_params_ 就能直接得到最好的参数搭配结果
    print(clf.best_params_)

    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']

    # 看一下具体的参数间不同数值的组合后得到的分数是多少
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))

    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_test, clf.predict(X_test)

   


# Tuning hyper-parameters for precision



E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Best parameters set found on development set:

{'C': 10, 'kernel': 'linear'}

Grid scores on development set:

0.764 (+/-0.149) for {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}
0.810 (+/-0.161) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.770 (+/-0.142) for {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
0.797 (+/-0.157) for {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
0.770 (+/-0.142) for {'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}
0.783 (+/-0.179) for {'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}
0.770 (+/-0.142) for {'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}
0.787 (+/-0.171) for {'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
0.893 (+/-0.093) for {'C': 1, 'kernel': 'linear'}
0.896 (+/-0.084) for {'C': 10, 'kernel': 'linear'}
0.895 (+/-0.087) for {'C': 100, 'kernel': 'linear'}
0.896 (+/-0.089) for {'C': 1000, 'kernel': 'linear'}

Detailed classification report:

The model is trained on the full development set.
The scores are computed on the full evaluation set.



NameError: name 'classification_report' is not defined

#### 逻辑回归

In [23]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LRclassifier = LogisticRegression(random_state = 0,verbose = 1,n_jobs = 8,penalty = 'l1',C=10)
LRclassifier.fit(X_train, y_train)

# Predicting the Test set results
LR_y_pred = LRclassifier.predict(X_test)

[LibLinear]

E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 8.
  " = {}.".format(effective_n_jobs(self.n_jobs)))


from sklearn.model_selection import cross_val_score
loss = cross_val_score(classifier,cro_X_train,cro_y_train,cv = 5,scoring='neg_log_loss')

In [24]:
LR_cm = confusion_matrix(y_test, LR_y_pred)
LR_cm

array([[801,  16],
       [ 26, 662]], dtype=int64)

In [25]:
print(-loss.mean())

NameError: name 'loss' is not defined

#### LR的网格搜索(调参)

In [47]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
 
#需要调优的参数
# 请尝试将L1正则和L2正则分开，并配合合适的优化求解算法（slover）
#tuned_parameters = {'penalty':['l1','l2'],
#                   'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]
#                   }
penaltys = ['l1','l2']
Cs = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
tuned_parameters = dict(penalty = penaltys, C = Cs)
 
lr_penalty= LogisticRegression()
grid= GridSearchCV(lr_penalty, tuned_parameters,cv=5, scoring='neg_log_loss')
grid.fit(X_train,y_train)
 
grid.cv_results_
 
print(-grid.best_score_)
print(grid.best_params_)



E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:43

E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:43

E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:43

E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\ml2\lib\site-packages\sklearn\linear_model\logistic.py:43

0.16191281069941071
{'C': 10, 'penalty': 'l1'}



test_means = grid.cv_results_[ 'mean_test_score' ]
test_stds = grid.cv_results_[ 'std_test_score' ]
train_means =grid.cv_results_['mean_train_score']
train_stds =grid.cv_results_[ 'std_train_score' ]

n_Cs = len(Cs)
number_penaltys = len(penaltys)
test_scores = np.array(test_means).reshape(n_Cs,number_penaltys)
train_scores = np.array(train_means).reshape(n_Cs,number_penaltys)
test_stds = np.array(test_stds).reshape(n_Cs,number_penaltys)
train_stds = np.array(train_stds).reshape(n_Cs,number_penaltys)
 
x_axis = np.log10(Cs)
for i, value in enumerate(penaltys):
    #pyplot.plot(log(Cs), test_scores[i], label= 'penalty:'   + str(value))
    pyplot.errorbar(x_axis, test_scores[:,i], yerr=test_stds[:,i] ,label = penaltys[i] +' Test')
    pyplot.errorbar(x_axis, train_scores[:,i], yerr=train_stds[:,i] ,label = penaltys[i] +' Train')
    
pyplot.legend()
pyplot.xlabel( 'log(C)' )                                                                                                      
pyplot.ylabel( 'neg-logloss' )

pyplot.show()

In [48]:
grid.cv_results_

{'mean_fit_time': array([0.01017451, 0.00976644, 0.04453692, 0.01095819, 0.01760077,
        0.01500497, 0.03514686, 0.01858182, 0.07785554, 0.02138767,
        0.06128216, 0.0198298 , 0.06424289, 0.01793494]),
 'std_fit_time': array([0.00160921, 0.00132796, 0.01101124, 0.0020328 , 0.01570002,
        0.00633315, 0.0120829 , 0.00384736, 0.0680771 , 0.00383265,
        0.01327992, 0.00115276, 0.02664637, 0.00372187]),
 'mean_score_time': array([0.00100341, 0.00099711, 0.00219908, 0.00299845, 0.00019917,
        0.00220022, 0.        , 0.00079737, 0.00079851, 0.00099745,
        0.00019951, 0.00240717, 0.00420671, 0.00241213]),
 'std_score_time': array([1.14297777e-05, 1.66142000e-06, 3.91957160e-03, 3.57786337e-03,
        3.98349762e-04, 3.92042532e-03, 0.00000000e+00, 7.45295862e-04,
        7.47194232e-04, 8.92229903e-04, 3.99017334e-04, 3.82497076e-03,
        4.75851017e-03, 3.83839760e-03]),
 'param_C': masked_array(data=[0.001, 0.001, 0.01, 0.01, 0.1, 0.1, 1, 1, 10, 10, 100,
    

In [54]:
#from sklearn.model_selection import train_test_split
#cross_X_train, cross_X_test, cross_y_train, cross_y_test = train_test_split(X_train,y_train, test_size=0.4, random_state=0)


#### 随机森林

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [27]:
RFclassifier = RandomForestClassifier(random_state = 0,n_estimators = 20,n_jobs = -1)
RFclassifier.fit(X_train, y_train)



RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=-1,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [28]:
# Predicting the Test set results
RF_y_pred = RFclassifier.predict(X_test)

In [32]:
print(SVMclassifier.score(X_train,y_train))
print(SVMclassifier.score(X_test,y_test))
print(LRclassifier.score(X_train,y_train))
print(LRclassifier.score(X_test,y_test))
print(RFclassifier.score(X_train,y_train))
print(RFclassifier.score(X_test,y_test))

0.9052783803326103
0.9122923588039867
0.9595083152566883
0.9720930232558139
0.9992769342010123
0.9627906976744186


In [30]:
RF_cm = confusion_matrix(y_test, RF_y_pred)
RF_cm

array([[807,  10],
       [ 46, 642]], dtype=int64)

AttributeError: 'LogisticRegression' object has no attribute 'classification_report'

#### 组合分类器,LightGBM

In [36]:
import lightgbm as lgb
import pandas as pd

In [48]:

#df = pd.DataFrame(df)
#lgb_train = lgb.Dataset(X_train, label=y_train)
#lgb_test = lgb.Dataset(X_test, label=y_test)
#lgb_train = lgb.Dataset(X_train, y_train)
lgb_train = pd.DataFrame(X_train, y_train)
lgb_test = pd.DataFrame(X_test,y_test)
#lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train)
lgb_train.to_csv("train.csv",index=False,sep=',')
lgb_test.to_csv("test.csv",index=False,sep=',')

## 需要改的地方

In [45]:
# load or create your dataset
df_train = pd.read_csv('train.csv', header=None, sep=',')
df_test = pd.read_csv('test.csv', header=None, sep=',')

lgby_train = df_train[0]
lgby_test = df_test[0]
lgbX_train = df_train.drop(0, axis=1)
lgbX_test = df_test.drop(0, axis=1)

Starting training...


TypeError: Wrong type(ndarray) for label.
It should be list, numpy 1-D array or pandas Series

In [ ]:
# save model to file
gbm.save_model('model.txt')

print('Starting predicting...')
# predict
y_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration)
# eval
print('The rmse of prediction is:', mean_squared_error(y_test, y_pred) ** 0.5)

In [38]:
gbm = lgb.LGBMRegressor(num_leaves=31,
                        learning_rate=0.05,
                        n_estimators=20)
gbm.fit(X_train_pandas, y_train,
        eval_set=[(X_test_pandas, y_test)],
        eval_metric='l1',
        early_stopping_rounds=5)

TypeError: Wrong type(ndarray) for label.
It should be list, numpy 1-D array or pandas Series